### ISSUE TITLE
Plans to increase language support?

### ISSUE THREAD

**Issue by miragecraft** [jensschnitzler/Gyre-Heros-Variable#2]
Was doing some stat finding with fontdrop.info, and I noticed that this font has less language support than I realized

Gyre Heros Variable:
686 glyphs and 90 supported languages

Being from Canada, French is sorely missed as I can see myself sprinkle it in my blog posts.

For curiosity sake I decided to do some cursory investigation into the number of glyphs and language support the fonts that I've been testing lately have...

Tex Gyre Heros
1090 glyphs and 97 supported languages

That's a LOT more glyphs for only a little more language support. I realized soon that Tex Gyre Heros is primarily designed for LaTex, so it is probably choke full of math and science glyphs that aren't commonly included in normal fonts, so I went and checked some other fonts I have laying around:

Arimo
3237 glyphs and 147 supported languages

Ok, that's a LOT, probably expected for something intended to replace Arial but overkill for normal usage.

Nimbus Sans L
759 glyphs and 105 supported languages

Interesting, the OG of open source Helvetica clone, the grandfather of all of them, only has 759 glyphs but boasts 105 supported languages while the expanded Tex Gyre Heros have less, probably due to all the math/science glyphs...

Hanken Grostesk
696 glyphs and 101 supported languages

Interesting, Hanken Grotesk was able to squeeze 101 languages out of 696 glyphs.

Libre Franklin
622 glyphs and 98 supported languages

Public Sans
645 glyphs and 100 supported languages

Similar story with Libre Franklin and Public Sans that's based on it.

Neue Haas Grotesk
538 glyphs and 95 supported languages

Have this one laying around for curiosity/comparison so I gave it a try in fontdrop, it's able to squeeze 95 supported languages out of only 538 glyphs!

It seems like there are languages that can be supported with minimal number of glyphs, maybe a good idea to try to get the "low hanging fruit" languages covered?

**Comment by iskrisis** [comment]
@miragecraft i am pretty sure the project wants to support as many languages as possible. Especially French. It's most likely just a mistake.

I would suggest though to try to bring a bit more constructive approach. If you can't directly contribute the missing glyphs it would be great if you could identify exactly which ones are required to get the support you want. This will make it a lot easier for someone else to come in and contribute the required glyphs.

**Comment by jensschnitzler** [comment]
I certainly plan to increase language support. Actually the glyphs file already contains a lot more glyphs than the exported fonts. But those glyphs are not compatible with each other for interpolation yet. In the attached screenshot you can see for example the glyphs marked red, which need to be cleaned up properly, before they can be exported in the variable font files.

<img width="1509" alt="Bildschirmfoto 2023-12-28 um 14 02 48" src="https://github.com/jensschnitzler/Gyre-Heros-Variable/assets/14975858/5dabe299-8232-40a6-bff6-98856e85207e">

**Comment by miragecraft** [comment]
> I certainly plan to increase language support. Actually the glyphs file already contains a lot more glyphs than the exported fonts. But those glyphs are not compatible with each other for interpolation yet. In the attached screenshot you can see for example the glyphs marked red, which need to be cleaned up properly, before they can be exported in the variable font files.

Awesome! Looking forward to it =)
